#pragma once

static const char kWebUi[] PROGMEM = R"HTML(
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="csrf" content="%CSRF%"><title>SKR SWD Flasher</title>
<style>
:root{color-scheme:dark;--bg:#10141b;--card:#1a2230;--ink:#edf3fb;--muted:#9eacc0;--accent:#45c4a1;--bad:#ff667a}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#0d1820,#15101e);font:16px system-ui;color:var(--ink)}
main{max-width:760px;margin:5vh auto;padding:24px}.card{background:var(--card);padding:26px;border:1px solid #2b394d;border-radius:16px;box-shadow:0 20px 50px #0008}
h1{margin:0 0 4px;font-size:1.7rem}.sub{color:var(--muted);margin:0 0 24px}.drop{display:block;border:2px dashed #40536b;border-radius:12px;padding:26px;text-align:center;cursor:pointer}.drop:hover{border-color:var(--accent)}
input[type=file]{display:none}button{border:0;border-radius:9px;padding:12px 17px;font-weight:700;cursor:pointer;background:var(--accent);color:#07130f;margin:10px 8px 0 0}button.secondary{background:#3b495d;color:var(--ink)}button:disabled{opacity:.4;cursor:not-allowed}
.bar{height:12px;background:#0b1017;border-radius:9px;overflow:hidden;margin:22px 0 10px}.fill{height:100%;width:0;background:linear-gradient(90deg,#30a9de,var(--accent));transition:width .25s}.row{display:flex;justify-content:space-between;gap:12px}.small{font-size:.86rem;color:var(--muted)}#message.error{color:var(--bad)}code{color:#b8e7da}.warning{border-left:3px solid #f2b84b;padding-left:12px;color:#f4dca8}.details{margin:18px 0;padding:14px;background:#111823;border-radius:10px;line-height:1.55}.details b{color:#dce8f7}.ok{color:var(--accent)}</style></head>
<body><main><section class="card"><h1>SKR Mini E3 V3.0 SWD Flasher</h1><p class="sub">Safe Marlin application update at <code>0x08002000</code></p>
<label class="drop" for="firmware"><strong id="filename">Choose a Marlin .bin file</strong><br><span class="small">Upload is followed automatically by a read-only controller and installed-firmware check.</span></label>
<input id="firmware" type="file" accept=".bin,application/octet-stream">
<div class="bar"><div class="fill" id="fill"></div></div><div class="row"><span id="state">Idle</span><span id="percent">0%</span></div>
<p id="message" class="small">Upload a firmware image to begin.</p>
<button id="upload" disabled>Upload &amp; preflight</button><button id="flash" disabled>Review, flash &amp; verify</button><button id="restore" class="secondary">Restore backup</button>
<div class="details small"><b>Live controller:</b> <span id="target">not probed</span><br><b>Uploaded identity:</b> <span id="candidate">none</span><br><b>Uploaded binary:</b> <span id="image">not inspected</span><br><b>Installed identity:</b> <span id="installed">not read</span><br><b>Installed binary:</b> <span id="installedImage">not read</span><br><b>Compatibility evidence:</b> <span id="evidence">not completed</span><br><b>Comparison:</b> <span id="comparison">not completed</span></div>
<p class="warning small">Flash is enabled only after preflight and requires typing <code>FLASH SKR</code>; recovery requires <code>RESTORE SKR</code>. Keep printer power on and do not unplug the SWD cable.</p>
<div class="small">Programmer: %BOARD% &middot; firmware %VERSION%</div>
</section></main>
<script>
const $=id=>document.getElementById(id),csrf=document.querySelector('meta[name=csrf]').content;
let selected=null,ready=false,lastStatus=null;
$('firmware').onchange=e=>{selected=e.target.files[0];$('filename').textContent=selected?selected.name:'Choose a Marlin .bin file';$('upload').disabled=!selected};
$('upload').onclick=()=>{if(!selected)return;let x=new XMLHttpRequest();x.open('POST','/api/upload');x.setRequestHeader('X-CSRF-Token',csrf);x.upload.onprogress=e=>{if(e.lengthComputable){let p=Math.round(e.loaded/e.total*100);$('fill').style.width=p+'%';$('percent').textContent=p+'%';$('state').textContent='Uploading'}};x.onload=()=>{if(x.status<200||x.status>=300)showError(x.responseText);poll()};let f=new FormData();f.append('firmware',selected);x.send(f)};
async function command(path,phrase){let entered=prompt('Type '+phrase+' to authorize this operation:','');if(entered!==phrase){showError('Authorization phrase did not match; nothing was erased.');return}try{let r=await fetch(path,{method:'POST',headers:{'X-CSRF-Token':csrf,'X-Flash-Confirm':entered}});if(!r.ok)showError(await r.text());else poll()}catch(e){showError(e.message)}}
$('flash').onclick=()=>{if(!lastStatus||!ready)return;let s=lastStatus,u=x=>x||'not embedded in binary';let review='FINAL PREFLIGHT REVIEW\n\nController: '+s.target_model+'\nDevice ID: '+hex(s.target_id,3)+'  Revision: '+hex(s.target_revision,4)+'\nSWD DP ID: '+hex(s.target_debug_port_id)+'\nUnique ID: '+s.target_uid+'\nFlash: '+Math.round(s.flash_bytes/1024)+' KiB\n\nInstalled: '+u(s.installed_firmware)+'\nInstalled printer: '+u(s.installed_machine)+'\nInstalled board/MCU: '+u(s.installed_board)+' / '+u(s.installed_mcu)+'\nInstalled CRC32: '+hex(s.installed_crc32)+'\n\nUploaded: '+u(s.uploaded_firmware)+'\nUploaded printer: '+u(s.uploaded_machine)+'\nUploaded board/MCU: '+u(s.uploaded_board)+' / '+u(s.uploaded_mcu)+'\nUploaded CRC32: '+hex(s.uploaded_crc32)+'\n\n'+s.uploaded_evidence+'\n\nThe files are different. Continue to phrase authorization?';if(confirm(review))command('/api/flash','FLASH SKR')};
$('restore').onclick=()=>command('/api/restore','RESTORE SKR');
function showError(s){$('message').textContent=s;$('message').className='error'}
function hex(v,n=8){return '0x'+Number(v||0).toString(16).padStart(n,'0')}
function summary(f,m,b,c,p,e,u,src){let a=[];if(f)a.push(f);if(m)a.push('printer: '+m);if(b)a.push('board: '+b);if(c)a.push('MCU: '+c);if(p)a.push('protocol: '+p);if(e)a.push('extruders: '+e);if(u)a.push('UUID: '+u);if(src)a.push('source: '+src);return a.length?a.join(' | '):'metadata not embedded in binary'}
async function poll(){try{let r=await fetch('/api/status',{cache:'no-store'}),s=await r.json();lastStatus=s;$('state').textContent=s.state.replaceAll('_',' ');$('percent').textContent=s.progress+'%';$('fill').style.width=s.progress+'%';$('message').textContent=s.message;$('message').className=s.state==='error'?'error':'small';ready=s.state==='ready'&&s.comparison_complete&&!s.identical;$('flash').disabled=!ready;if(s.target_id)$('target').textContent=s.target_model+', DEV_ID '+hex(s.target_id,3)+', revision '+hex(s.target_revision,4)+', SWD DP '+hex(s.target_debug_port_id)+', '+Math.round(s.flash_bytes/1024)+' KiB, UID '+s.target_uid;$('installed').textContent=summary(s.installed_firmware,s.installed_machine,s.installed_board,s.installed_mcu,s.installed_protocol,s.installed_extruders,s.installed_uuid,s.installed_source_url);$('candidate').textContent=summary(s.uploaded_firmware,s.uploaded_machine,s.uploaded_board,s.uploaded_mcu,s.uploaded_protocol,s.uploaded_extruders,s.uploaded_uuid,s.uploaded_source_url);$('image').textContent=s.image_size?s.image_size+' bytes, load '+hex(s.image_load_address)+', SP '+hex(s.uploaded_initial_sp)+', reset '+hex(s.uploaded_reset_vector)+', CRC32 '+hex(s.uploaded_crc32):'not inspected';$('installedImage').textContent=s.comparison_complete?s.image_size+' compared bytes, SP '+hex(s.installed_initial_sp)+', reset '+hex(s.installed_reset_vector)+', CRC32 '+hex(s.installed_crc32):'not read';$('evidence').textContent=s.uploaded_evidence||'not completed';$('comparison').textContent=s.comparison_complete?(s.identical?'exact byte and CRC32 match - already installed':'different image - eligible to flash'):'not completed';$('comparison').className=s.comparison_complete&&!s.identical?'ok':''}catch(e){}setTimeout(poll,600)}poll();
</script></body></html>)HTML";
